
build:
  version: 2.0

accounts:
  message: "Welcome to Eazy Bank accounts related qa api"
  contactDetails:
    name: "Venkat Rajulapati-QAdeveloper"
    email: "v.raju@gmail.com"
  onCallSupport:
    - 5557775555
    - 7788995454
